Add support for converting error bodies in HTTP 4xx responses
slackhq/EitherNet pull request #12
Opened 2020-10-20 20:17 UTC by ZacSweers

Resolves #6

This adds support for converting error bodies.

Changes:
* `HttpFailure` now uses the same error generic
* Endpoints can be opted in to parsing error bodies via `@DecodeErrorBody`. Zero-length bodies will be skipped
* A `@StatusCode` annotation is passed along to the converter for contextual decoding as needed per status code. We may also want to offer the headers here some day, but will save that for when someone asks for it.

2020-10-20 20:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackhq/EitherNet?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackhq/EitherNet?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackhq/EitherNet?pullRequest=12) it.</sub>

2020-10-21 02:06 UTC, adamsp requested changes
Couple of documentation fixes, but more importantly I think we should surface 5xx errors as `HttpFailure`, since right now they show up as `UnknownFailure`.

2020-10-22 00:19 UTC, ZacSweers commented on src/main/java/com/slack/eithernet/ApiResult.kt
> +                      val statusCode = createStatusCode(response.code())
Good point (especially with the Retrofit doc you linked me separately). Done in 1d34042

2020-10-22 02:13 UTC, adamsp approved these changes
Did you know there are _no_ good Giphy results for "ethernet"? Unfortunate.

2020-10-22 06:55 UTC, merged